#parameters:
#    app.path.images: /public/assets/uploads

vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /assets/uploads
            upload_destination: '%kernel.project_dir%/public/assets/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
